application: swarmerme
version: 1
runtime: python27
api_version: 1
threadsafe: yes


handlers:
- url: /$
  static_files: build/index.html
  upload: build/index.html

- url: /(.*)/$
  static_files: build/\1/index.html
  upload: build/.*/index.html

- url: /(.+)
  static_files: build/\1
  upload: build/(.*)


skip_files:
  - ^(.*/)?app\.yaml
  - ^(.*/)?app\.yml
  - ^(.*/)?#.*#
  - ^(.*/)?.*~
  - ^(.*/)?.*\.py[co]
  - ^(.*/)?.*/RCS/.*
  - ^(.*/)?\..*
  - ^(.*/)?tests$
  - ^(.*/)?test$
  - ^test/(.*/)?
  - ^COPYING.LESSER
  - ^README\..*
  - \.gitignore
  - ^\.git/.*
  - \.*\.lint$
  - ^fabfile\.py
  - ^testrunner\.py
  - ^grunt\.js
  - ^node_modules/(.*/)?
